<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.7" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\flaxseed_web.ServiceDefaults\flaxseed_web.ServiceDefaults.csproj" />
    <ProjectReference Include="..\flaxseed_web.Web\flaxseed_web.Web.csproj" />
  </ItemGroup>

</Project>
